### ISSUE TITLE
Are you going to make a binary release when done?

### ISSUE THREAD

**Issue by iandstanley** [pgregory/agon-light-invaders#1]

**Comment by pgregory** [comment]
There are a couple of very old releases, look at the releases section to the right in the code tab. I haven't done an updated release for a bit as it hasn't been working on device, only emulator, I need to get it working again on device.

**Comment by iandstanley** [comment]
I’ll have a look at the releases section againI’m also creating an awesome list for the agon light GitHub.com/iandstanley/Awesome-Agon-Light/On 13 Nov 2023, at 16:11, Paul Gregory ***@***.***> wrote:﻿
There are a couple of very old releases, look at the releases section to the right in the code tab. I haven't done an updated release for a bit as it hasn't been working on device, only emulator, I need to get it working again on device.
